### ISSUE TITLE
train.txt,valid.txt

### ISSUE THREAD

**Issue by world2025** [talebolano/resnet_lstm_Urban_Region_Function_Classification#1]

**Comment by world2025** [comment]
你好，请问可以分享一下train.txt,valid.txt文件吗？

**Comment by talebolano** [comment]
这个可能根据每个人数据存储的位置不同而有变化

**Comment by world2025** [comment]
@talebolano好的

**Comment by world2025** [comment]
@talebolano还有就是您是做了其他预处理是吗？我这训练达不到您的结果

**Comment by talebolano** [comment]
@tkone2018 没有其他操作，请参考确认[UrbanRegionFunctionClassification](https://github.com/czczup/UrbanRegionFunctionClassification)中对visit数据的处理，确保visit的数据处理正确，此外在验证集上的精度要比线上测的低不少。可以尝试模型融合、tta等方法增强线上结果

**Comment by world2025** [comment]
@talebolano 好的，谢谢
